from fpdf import FPDF
import markdown
import tempfile
import os

class BeautifulReportPDF(FPDF):
    def __init__(self, incident_date="Unknown Date"):
        super().__init__()
        self.incident_date = incident_date

    def header(self):
        # Logo/Header
        self.set_font("helvetica", "B", 16)
        self.set_text_color(220, 53, 69) # Red color for warning
        self.cell(0, 10, "PROJECT NECROMANCER", align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_font("helvetica", "I", 12)
        self.set_text_color(100, 100, 100)
        self.cell(0, 10, f"Automated AI Incident Report - {self.incident_date}", align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()}", align="C")

def generate_pdf_from_markdown(md_text, incident_date="Unknown Date"):
    pdf = BeautifulReportPDF(incident_date)
    pdf.add_page()
    
    # We use python-markdown to convert the markdown generated by the AI to HTML.
    # fpdf2's write_html understands basic HTML tags.
    html_content = markdown.markdown(md_text)
    
    # Sometimes Ollama markdown has artifacts, we just pass the HTML
    pdf.set_font("helvetica", size=11)
    
    # Write HTML
    pdf.write_html(html_content)
    
    # Output to bytes
    return pdf.output()
